# Generated by Django 3.1.1 on 2020-09-16 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('registry_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registry',
                'verbose_name_plural': 'Registries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('in_stock_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_status', models.CharField(default='AVAILABLE', max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_registry_api.product')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', related_query_name='gift', to='gift_registry_api.registry')),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
                'unique_together': {('registry', 'product')},
            },
        ),
    ]
