# Generated by Django 3.1.1 on 2020-09-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('brand', models.CharField(max_length=128, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('in_stock_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
