# Generated by Django 3.1.1 on 2020-09-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gift_registry_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registry',
                'verbose_name_plural': 'Registrys',
            },
        ),
        migrations.CreateModel(
            name='RegistryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_registry_api.product')),
                ('registry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_registry_api.registry')),
            ],
            options={
                'verbose_name': 'Registry Product',
                'verbose_name_plural': 'Registry Products',
                'unique_together': {('registry_id', 'product_id')},
            },
        ),
    ]
