# Generated by Django 3.1.1 on 2020-09-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry_api', '0002_registry_registryproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registryproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='registryproduct',
            old_name='registry_id',
            new_name='registry',
        ),
    ]
