# Generated by Django 3.1.1 on 2020-09-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_registry_api', '0003_auto_20200914_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='user',
            new_name='registry_owner',
        ),
        migrations.AddField(
            model_name='registry',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='registries', to='gift_registry_api.Product'),
        ),
        migrations.DeleteModel(
            name='RegistryProduct',
        ),
    ]
